In [2]:
import numpy as np
import pandas as pd
import torch

In [8]:
df = pd.read_csv('GB1/fitness.csv')
#rename fit to fitness
df.rename(columns={'fit':'fitness'}, inplace=True)
df[['Combo', 'fitness']].to_csv('GB1/fitness.csv', index=False)
df

,Combo,muts,fitness,zs score,num_muts,AA1,AA2,AA3,AA4
0,AMHG,V39A:D40M:G41H:V54G,0.000000,147.39927,4,A,M,H,G
1,QPEI,V39Q:D40P:G41E:V54I,0.000000,53.49178,4,Q,P,E,I
2,GMYW,V39G:D40M:G41Y:V54W,0.000000,134.21443,4,G,M,Y,W
3,KWNA,V39K:D40W:G41N:V54A,0.001791,145.52714,4,K,W,N,A
4,QDRA,V39Q:G41R:V54A,0.004730,139.14162,3,Q,D,R,A
...,...,...,...,...,...,...,...,...,...
149356,CCRA,V39C:D40C:G41R:V54A,0.009981,141.02978,4,C,C,R,A
149357,QSSK,V39Q:D40S:G41S:V54K,0.004755,145.35619,4,Q,S,S,K
149358,IAFG,V39I:D40A:G41F:V54G,3.028731,149.25890,4,I,A,F,G
149359,TILI,V39T:D40I:G41L:V54I,0.003469,141.88873,4,T,I,L,I
149360,LLPC,V39L:D40L:G41P:V54C,0.008662,76.27056,4,L,L,P,C

In [9]:
df = pd.read_csv('TrpB/fitness.csv')
#rename fit to fitness
df[['Combo', 'fitness']].to_csv('TrpB/fitness.csv', index=False)
df

,Combo,AA1,AA2,AA3,AA4,# Stop,fitness,active,EvMutation,Triad Score,esm2_t33_650M_UR50D-Naive,ESM2 Ranking,Triad Inverse Ranking,Triad Score AF,y_Potts
0,AAAA,A,A,A,A,0,0.074455,True,-13.970285,-1425.39688,-18.566208,5558.0,130436.0,-1502.55370,0.096299
1,AAAC,A,A,A,C,0,0.056314,True,-16.150133,-1421.17781,-20.513588,9696.0,100696.0,-1497.41323,0.094638
2,AAAD,A,A,A,D,0,0.014342,False,-14.703334,-1422.67840,-21.894038,13980.0,112111.0,-1492.81092,0.047427
3,AAAE,A,A,A,E,0,0.012914,False,-14.950169,-1419.72829,-21.987710,14342.0,89424.5,-1492.18555,0.052405
4,AAAF,A,A,A,F,0,0.005161,False,-16.150133,-1425.82286,-24.114601,24124.0,132911.0,-1490.52111,0.052611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159124,YYYS,Y,Y,Y,S,0,0.016578,False,-23.215630,-1427.95970,-32.565129,98586.0,143248.0,-1496.76790,0.000000
159125,YYYT,Y,Y,Y,T,0,0.030715,False,-26.169945,-1425.21459,-35.770307,128729.0,129377.0,-1491.91485,0.073058
159126,YYYV,Y,Y,Y,V,0,0.000000,False,-26.802021,-1423.64236,-35.435290,125970.0,119035.0,-1494.90492,0.076044
159127,YYYW,Y,Y,Y,W,0,0.000000,False,-26.912713,-1425.79403,-35.939902,130141.0,132751.0,-1487.24063,0.074841
159128,YYYY,Y,Y,Y,Y,0,0.000000,False,-26.912713,-1414.78427,-37.316769,140115.0,56345.0,-1482.82860,0.079369

In [16]:
data = np.load('GB1/GB1_ESM2_4site.npy')
data = data.reshape(data.shape[0], -1)
data = torch.tensor(data, dtype=torch.float32)
torch.save(data, 'GB1/ESM2_x.pt')

In [17]:
test = torch.load('GB1/ESM2_x.pt')
test.shape

torch.Size([149361, 5120])

In [18]:
data = np.load('TrpB/TrpB_ESM2_4site.npy')
data = data.reshape(data.shape[0], -1)
data = torch.tensor(data, dtype=torch.float32)
torch.save(data, 'TrpB/ESM2_x.pt')

In [19]:
test = torch.load('TrpB/ESM2_x.pt')
test.shape

torch.Size([159129, 5120])

In [15]:
test = torch.load('GB1/georgiev_x.pt')
test.shape

torch.Size([149361, 76])